results_dir: experiments/tokenizer
cloud_save_path: experiments/tokenizer
compile: False 
global_seed: 42
log_every: 50
vis_every: 5000
save_epochs: 1
mixed_precision: bf16
no_local_save: True

dataset: imagenet
data_path: ./ImageNet/train
image_size: 256
content_degradation: resolution_power
causal_encoder: True
causal_decoder: False
degradation_prob: 0.2
degradation_power: 1.5
dynamic_resolution_prob: 0
max_image_size: 256
min_image_size: 256

vq_model: VQ-16
tau: 0.07
ema: False 
num_codebooks: 1
codebook_size: 8192
codebook_embed_dim: 8
entropy_loss_ratio: 0.0
vq_loss_ratio: 1.0
commit_loss_beta: 0.25
reconstruction_weight: 1.0
perceptual_weight: 1.0
perceptual_warmup: 10000
disc_weight: 0.2
use_diff_aug: True 
disc_cr_loss_weight: 4.0
disc_start: 40000
disc_type: dino
disc_loss: hinge
gen_loss: hinge
lecam_loss_weight: 0.001

enc_type: siglip2
encoder_model: siglip2_base
encoder_pretrained: True
encoder_patch_size: 16
encoder_tuning_method: full
dec_type: siglip2
decoder_model: siglip2_base
decoder_pretrained: False 
decoder_patch_size: 16
decoder_tuning_method: full
num_latent_tokens: 256

repa: False
repa_model: siglip2
repa_patch_size: 16
repa_proj_dim: 1024
repa_loss_weight: 0.5
repa_layer_indices: 1

epochs: 50
lr: 1.0e-4
optimizer: adam
lr_scheduler: cosine
weight_decay: 0.0001
beta1: 0.9
beta2: 0.95
max_grad_norm: 1.0
global_batch_size: 256